<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Twig template for render content
 */
function smile_block_theme($existing, $type, $theme, $path) {
  return [
    'smile_block' => [
      'variables' => [
        'list' => [],
      ],
    ],
  ];
}

///**
// * Implements hook_form_FORM_ID_alter().
// */
//function smile_block_form_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {
//  $block = $form_state->getFormObject()->getEntity();
//  $form['third_party_settings']['smile_block']['entity_count'] = [
//    '#type' => 'number',
//    '#title' => t('Entities number'),
//    '#description' => t('Customize the styling of this block by adding CSS classes.'),
//    '#default_value' => $block->getThirdPartySetting('smile_block', 'entity_count'),
//  ];
//}
