<?php

use Drupal\Core\Entity\EntityInterface;

function custom_cron_cron() {
  $data = \Drupal::database();
  $conf = \Drupal::config("custom_cron.set_parameters");
  $limit = $conf->get('items');
  $period = time() - $conf->get('period');

  $result = $data->select('node_field_data', 'nfd')
    ->condition('status', '1',)
    ->condition('changed',$period,'<')
    ->fields('nfd', ['nid','type'])
    ->orderBy('changed', 'DESC')
    ->range(0,$limit)
    ->execute();

  foreach ($result as $nids) {
    $queue = \Drupal::queue('CustomWorker');
    $item = new \stdClass();
    $item->nid = $nids->nid;
    $item->type = $nids->type;
    $queue->createItem($item);
  }
}

