<?php

use Drupal\Component\Render\PlainTextOutput;
use Drupal\Core\Render\Element;
use Drupal\smile_entity\Entity\SmileEntity;

/**
 * @file
 * Twig template for render content
 */
function smile_entity_theme($existing, $type, $theme, $path) {
  return  [
    'smile_entity' => [                            // the entity id
      'path' => $path . '/templates',          // template directory in module or theme
      'template'  => 'smile-entity',                // defines base template as /artwork.html.twig
      'render element' => 'elements',          // Theme API call to define the container of the entity in the render array
      // The entity will be prefixed with a hash sign as ['elements']['#smile_entity']
    ],
  ];
}

/**
 * @param $variables
 *
 * @throws \Drupal\Core\Entity\EntityMalformedException
 */
function template_preprocess_smile_entity(&$variables) {
  // Helpful $content variable for templates.
  $variables['content'] = [];
  foreach (\Drupal\Core\Render\Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  /** @var SmileEntity $entity */
  $entity = $variables['elements']['#smile_entity'];
  //Set variables to template.
  $variables['label'] = $entity->label();
  $variables['url'] = $entity->toUrl()->toString();
  $variables['changed'] = \Drupal::service('date.formatter')->format($entity->getChangedTime(), 'short');
  $variables['body'] = $entity->get('body')->value;
}


